### ISSUE TITLE
Changing tdim for pretrained model

### ISSUE THREAD

**Issue by ranjith1604** [kkoutini/PaSST#10]
Thanks for sharing such great work! I want to use the pre-trained model but changing input_tdim is giving an error. My audio clips are relatively small and hence i need a smaller input_tdim. How do I do that? The error I get is due to the pretrained layer's size not equal to the current size of the model(After using input_tdim)

**Comment by kkoutini** [comment]
Hi, can you give more details about the error?
In general, if the audio is shorter than expected, you can leave input_tdim and it should be automatically handled.

**Comment by kkoutini** [comment]
Hi, you can keep the input_tdim to its default value. the model should handle shorter audio clips.
