### ISSUE TITLE
I have a problem. why convert wav to mp3?

### ISSUE THREAD

**Issue by zdj97** [kkoutini/PaSST#29]
I  have a problem. why convert .wav to .mp3 and 32k? And what would happen if converting to 16K and use .wav file?

**Comment by zdj97** [comment]
Sor to ask this question. I am not sure if .wav file would cause problem to creat h5py.

**Comment by kkoutini** [comment]
Hi, I used mp3 to reduce the size of the dataset and overcome the slowdown from I/O.
You can use wav as well, in that case, there is no need to decode the file [here](https://github.com/kkoutini/PaSST/blob/c57eb20a2f3eba0f253aa14e42d6dfb078e3d15a/audioset/dataset.py#L192)

Keep in mind if you change the samping rate,  you need to adjust the STFT settings [here](https://github.com/kkoutini/PaSST/blob/c57eb20a2f3eba0f253aa14e42d6dfb078e3d15a/ex_audioset.py#L54) to match.

**Comment by zdj97** [comment]
Thanks! That is very useful for me.
