### ISSUE TITLE
Error when trying to pip install repo

### ISSUE THREAD

**Issue by Antoine101** [kkoutini/PaSST#39]
Hi @kkoutini,

I get an error when running the following line after my conda env creation:
![image](https://github.com/kkoutini/PaSST/assets/48209504/90d619f7-65d0-42d5-b504-f478c3b3f5b6)

Any idea?

This line was working a couple of months ago when I had created a first environment. But not anymore it seems.

Many thanks

Antoine

**Comment by kkoutini** [comment]
Hi!
I uploaded to the package to pypi
can you try to install it directly like this:
```bash
pip install hear21passt
```

**Comment by Antoine101** [comment]
Thank you Khaled, it installed correctly!
