### ISSUE TITLE
Fixing weights for fine-tuning?

### ISSUE THREAD

**Issue by Antoine101** [kkoutini/PaSST#44]
Hi Khaled,

Do you fix weights of embeddings and attention blocks after loading pretrained checkpoints for finetuning, or is it just an initialization and they are further updated through finetuning?
I can't really find the answer in your code.

Many thanks.

**Comment by kkoutini** [comment]
Hi Antoine,
Sorry for the late reply.
For fine-tuning, I do not freeze any parameters, I load the pretrained model and fine-tune it for very few epochs.

**Comment by Antoine101** [comment]
No worries! Ok great, thanks for the clarification!
